substitutions:
  devicename: basement-main-usw-light
  shortname: "Basement Main USW"
  fullname: "Basement Main USW Light"
  ipPrefix:  !secret ip_prefix
  id: "36"

<<: !include base.yaml

esphome:
  name: ${devicename}
  comment: "${ipPrefix}.${id}"
  on_boot:
    then:
      - light.turn_on: 
          id: downlight
          brightness: 100%
          cold_white: 45%
          warm_white: 100%

libretuya:
  board: wb3s
  framework:
    version: dev

time:
  - platform: homeassistant
    id: homeassistant_time

light:
  - platform: rgbww
    id: downlight
    name: ${shortname}
    red: red
    green: green
    blue: blue
    cold_white: cold_white
    warm_white: warm_white
    cold_white_color_temperature: 6535 K
    warm_white_color_temperature: 2702 K
    default_transition_length: 0s
    color_interlock: true
    restore_mode: RESTORE_DEFAULT_ON

output:
  - platform: ledc
    id: red
    pin: D8
  - platform: ledc
    id: green
    pin: D3
  - platform: ledc
    id: blue
    pin: D2
  - platform: ledc
    id: cold_white
    pin: D9
  - platform: ledc
    id: warm_white
    pin: D4