substitutions:
  hostname: back-entry-light
  name: back-entry-light
  display_name: "Back Entry Light"
  ipPrefix:  !secret ip_prefix
  id: "19"

<<: !include base.yaml

esphome:
  name: ${hostname}

libretuya:
  #manufacturer = Cloudy Bay
	#name = Recessed 15W RGBCT Downlight
  #profiles oem-bk7231s-ceiling-light-ty-1.3.2-sdk-1.0.2-40.00
  board: wb3s
  framework:
    version: dev #latest

time:
  - platform: homeassistant
    id: homeassistant_time

light:
  - platform: rgbww
    name: ${display_name}
    red: red
    green: green
    blue: blue
    cold_white: cold_white
    warm_white: warm_white
    cold_white_color_temperature: 6535 K
    warm_white_color_temperature: 2702 K
    restore_mode: RESTORE_DEFAULT_OFF

output:
  - platform: ledc
    id: red
    pin: D8
  - platform: ledc
    id: green
    pin: D3
  - platform: ledc
    id: blue
    pin: D2
  - platform: ledc
    id: cold_white
    pin: D9
  - platform: ledc
    id: warm_white
    pin: D4