substitutions:
  devicename: lower-foyer-light
  fullname: "Lower Foyer Light"
  shortname: "Lower Foyer"
  ipPrefix:  !secret ip_prefix
  id: "20"

<<: !include base.yaml

esphome:
  name: ${devicename}
  comment: ${fullname}

libretuya:
  board: wb3s
  framework:
    version: dev

time:
  - platform: homeassistant
    id: homeassistant_time

light:
  - platform: rgbww
    name: ${shortname}
    red: red
    green: green
    blue: blue
    cold_white: cold_white
    warm_white: warm_white
    cold_white_color_temperature: 6535 K
    warm_white_color_temperature: 2702 K
    restore_mode: RESTORE_DEFAULT_OFF

output:
  - platform: ledc
    id: red
    pin: D8
  - platform: ledc
    id: green
    pin: D3
  - platform: ledc
    id: blue
    pin: D2
  - platform: ledc
    id: cold_white
    pin: D9
  - platform: ledc
    id: warm_white
    pin: D4