substitutions:
  devicename: basement-tv-ls-light
  shortname: "Basement TV LS"
  fullname: "Basement TV LS Light"
  ipPrefix:  !secret ip_prefix
  id: "45"

<<: !include base.yaml

esphome:
  name: ${devicename}
  comment: "${ipPrefix}.${id}"
  on_boot:
    then:
      - light.turn_on: 
          id: downlight
          brightness: 100%
          cold_white: 45%
          warm_white: 100%

bk72xx:
  board: generic-bk7231t-qfn32-tuya

time:
  - platform: homeassistant
    id: homeassistant_time

light:
  - platform: rgbww
    id: downlight
    name: ${shortname}
    color_interlock: true
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_cold
    warm_white: output_warm
    default_transition_length: 0s
    restore_mode: RESTORE_DEFAULT_ON

output:
  - platform: libretiny_pwm
    id: output_red
    pin: P9
  - platform: libretiny_pwm
    id: output_green
    pin: P24
  - platform: libretiny_pwm
    id: output_blue
    pin: P26
  - platform: libretiny_pwm
    id: output_cold
    pin: P8
  - platform: libretiny_pwm
    id: output_warm
    pin: P6