
esphome:
  name: ${devicename}
  comment: ${ipPrefix}.${id}

wifi:
  networks:
    ssid: "SALNET_IoT"
    password: !secret iot_psswd
    manual_ip:
      static_ip: "${ipPrefix}.${id}"
      gateway: !secret iot_gateway
      subnet: !secret subnet
      dns1: !secret local_ip
      dns2: 1.1.1.1
  fast_connect: true
  reboot_timeout: 0s

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${fullname} AP
    password: !secret fallback_psswd

captive_portal:

logger:

ota:
  password: !secret ota_psswd

#web_server: 

api:
  encryption:
    key: !secret esphome_encryption_key 
  reboot_timeout: 0s

time:
  - platform: homeassistant
    id: homeassistant_time

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address: ${fullname}"
      update_interval: 300min
    mac_address:
      name: "MAC Address: ${fullname}"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal dB: ${fullname}"
    id: "andy_phone_charger_manual_id_wifi_signal_db"
    update_interval: 15min
    entity_category: "diagnostic"

button:
  - platform: restart
    name: "Restart: ${fullname}"
    entity_category: "config"
  - platform: safe_mode
    name: "Restart (Safe Mode): ${fullname}"
    entity_category: "config"