substitutions:
  devicename: dryer-current
  fullname: "Dryer Current"
  ipPrefix:  !secret ip_prefix
  id: "9"

<<: !include base.yaml

esphome:
  name: ${devicename}
  comment: ${ipPrefix}.${id}
  platform: ESP8266
  board: d1_mini_lite

sensor:
  - platform: ct_clamp
    sensor: adc_sensor
    name: ${fullname}
    unit_of_measurement: "A"
    icon: "mdi:lightning-bolt-circle"
    id: dryer_current
    update_interval: 60s
    filters:
      - filter_out: nan
      - calibrate_linear:
          - 0.0 -> 0.0
          - 0.058 -> 7.00
              
  - platform: adc
    pin: A0
    id: adc_sensor

binary_sensor:
  - platform: template
    name: "${fullname} Status"
    filters:
      - delayed_on: 240s
      - delayed_off: 240s
    lambda: |-
      if (isnan(id(dryer_current).state)) {
        return {};
      } else if (id(dryer_current).state > 3) {
        return true;
      } else {
        return false;
      }