substitutions:
  devicename: holiday-plug-1
  fullname: "Holiday Plug 1"
  ipPrefix:  !secret ip_prefix
  id: "13"

packages:
  device_base: !include base.yaml

esp8266:
  board: esp01_1m
  restore_from_flash: true
    
#Button
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO1
      mode: INPUT
    id: btn
    internal: true
    on_press:
      - switch.toggle: relay
      
  #- platform: status
  #  name: ${display_name} Status
  #  id: ${name}_status

#Led
output:
  - platform: gpio
    id: led1
    pin:
      number: GPIO13
      inverted: True

light:
  - platform: binary
    internal: true
    output: led1
    id: status_led
    restore_mode: RESTORE_DEFAULT_ON

#Relay    
switch:
- platform: gpio
  id: relay
  name: "${devicename}"
  pin: GPIO14
  restore_mode: RESTORE_DEFAULT_ON
  on_turn_on:
    - light.turn_on: status_led
  on_turn_off:
    - light.turn_off: status_led