substitutions:
  devicename: master-night-light
  fullname: "Master Night Light"
  ipPrefix:  !secret ip_prefix
  id: "11"

packages:
  device_base: !include base.yaml
    
esp8266:
  board: esp01_1m
  restore_from_flash: true

# Configuration for TGWF115PQM (Small 10A plug)
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      inverted: True
    id: physical_button
    internal: true
    on_press:
      then:
        - switch.toggle: relay
        # Note that blue LED appears to be tied to relay state internally (i.e. electrically)
    
switch:
  # Main plug control relay
  - platform: gpio
    name: ${fullname}
    id: relay
    pin: GPIO14
    restore_mode: ALWAYS_OFF
    
  # Used for Status LED below, but could be repurposed!
  # - platform: gpio
  #   name: "${name} Green LED"
  #   id: "led_green"
  #   pin: GPIO13
  #   restore_mode: ALWAYS_ON
  
status_led:
  # Use Green LED as ESPHome's built-in status indicator
  pin:
    number: GPIO13
    inverted: False