substitutions:
  devicename: smart-plug
  fullname: "Smart Plug"
  ipPrefix:  !secret ip_prefix
  id: "3"

packages:
  device_base: !include base.yaml

esp8266:
  board: esp01_1m
  restore_from_flash: true
    
#Button
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO1
      mode: INPUT
    name: "${name}_button"
    internal: true
    on_press:
      - switch.toggle: relay
      
  #- platform: status
  #  name: ${display_name} Status
  #  id: ${name}_status

#Led
output:
  - platform: gpio
    id: led1
    pin:
      number: GPIO13
      inverted: True

light:
  - platform: binary
    internal: true
    output: led1
    id: status_led
    restore_mode: ALWAYS_OFF

#Relay    
switch:
- platform: gpio
  id: relay
  name: "${fullname}"
  pin: GPIO14
  restore_mode: ALWAYS_OFF
  on_turn_on:
    - light.turn_on: status_led
  on_turn_off:
    - light.turn_off: status_led