substitutions:
  devicename: sump-level
  fullname: "Sump Level"
  ipPrefix:  !secret ip_prefix
  id: "7"

packages:
  device_base: !include base.yaml
    
esp8266:
  board: d1_mini_lite
  restore_from_flash: true

sensor:
  - platform: ultrasonic
    trigger_pin: D1
    echo_pin: D2
    unit_of_measurement: "cm"
    icon: "mdi:cup-water"
    accuracy_decimals: 0
    name: ${fullname}
    update_interval: 120s
  
    filters:
      - lambda: return 48-(x*100);
      - filter_out: nan