substitutions:
  devicename: water-softener
  fullname: "Water Softener Salt Level"
  ipPrefix:  !secret ip_prefix
  id: "2"

packages:
  device_base: !include base.yaml
    
esp8266:
  board: d1_mini
  restore_from_flash: true

sensor:
  - platform: ultrasonic
    trigger_pin: D1
    echo_pin: D2
    unit_of_measurement: "%"
    icon: "mdi:cup-water"
    accuracy_decimals: 0
    name: ${fullname}
    update_interval: 1d
  
    filters:
      - lambda: return ((85-((x*100)-9))/85)*100;
      - filter_out: nan